### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by DeveshGoyal26** [Saradhii/warlike-current-5989#4]
### Tasks
- [x]  Cart Page style
- [x]  Cart page heading
- [x]  Cart page product listing
- [x]  Cart page total
- [x]  Cart check out button
- [x]  Cart page functionality
