### ISSUE TITLE
Information and Shipping Page

### ISSUE THREAD

**Issue by DeveshGoyal26** [Saradhii/warlike-current-5989#6]
### Tasks
- [x] Contact information
- [x] User Profile/User Info
- [x] Shipping address
- [x] Address form
- [x] Products, total and discount
- [x] User Info on Shipping
- [x] Shipping method
